/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UAvatar: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.9.0_b8e413c903418fd73430c97a9cec7af3/node_modules/@nuxt/ui/dist/runtime/components/Avatar.vue')['default']
    UBadge: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.9.0_b8e413c903418fd73430c97a9cec7af3/node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UButton: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.9.0_b8e413c903418fd73430c97a9cec7af3/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCard: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.9.0_b8e413c903418fd73430c97a9cec7af3/node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    UColorModeButton: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.9.0_b8e413c903418fd73430c97a9cec7af3/node_modules/@nuxt/ui/dist/runtime/components/color-mode/ColorModeButton.vue')['default']
    UFooter: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.9.0_b8e413c903418fd73430c97a9cec7af3/node_modules/@nuxt/ui/dist/runtime/components/Footer.vue')['default']
    UHeader: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.9.0_b8e413c903418fd73430c97a9cec7af3/node_modules/@nuxt/ui/dist/runtime/components/Header.vue')['default']
    UIcon: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.9.0_b8e413c903418fd73430c97a9cec7af3/node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    USeparator: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.9.0_b8e413c903418fd73430c97a9cec7af3/node_modules/@nuxt/ui/dist/runtime/components/Separator.vue')['default']
  }
}
