/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ComparisonSection: typeof import('./src/components/ComparisonSection.vue')['default']
    CtaSection: typeof import('./src/components/CtaSection.vue')['default']
    FeaturesSection: typeof import('./src/components/FeaturesSection.vue')['default']
    HeroSection: typeof import('./src/components/HeroSection.vue')['default']
    MockupPreview: typeof import('./src/components/MockupPreview.vue')['default']
    PricingSection: typeof import('./src/components/PricingSection.vue')['default']
    QuoteBand: typeof import('./src/components/QuoteBand.vue')['default']
    StepsSection: typeof import('./src/components/StepsSection.vue')['default']
    TestimonialsSection: typeof import('./src/components/TestimonialsSection.vue')['default']
    TrustBand: typeof import('./src/components/TrustBand.vue')['default']
    UAvatar: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+extensions@3.20.1_@tiptap+core@3.20.1_@tiptap+pm@3.20.1__@tiptap_1b0adad71e75a16afa4f2635bf844052/node_modules/@nuxt/ui/dist/runtime/components/Avatar.vue')['default']
    UBadge: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+extensions@3.20.1_@tiptap+core@3.20.1_@tiptap+pm@3.20.1__@tiptap_1b0adad71e75a16afa4f2635bf844052/node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UButton: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+extensions@3.20.1_@tiptap+core@3.20.1_@tiptap+pm@3.20.1__@tiptap_1b0adad71e75a16afa4f2635bf844052/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCard: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+extensions@3.20.1_@tiptap+core@3.20.1_@tiptap+pm@3.20.1__@tiptap_1b0adad71e75a16afa4f2635bf844052/node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    UColorModeButton: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+extensions@3.20.1_@tiptap+core@3.20.1_@tiptap+pm@3.20.1__@tiptap_1b0adad71e75a16afa4f2635bf844052/node_modules/@nuxt/ui/dist/runtime/components/color-mode/ColorModeButton.vue')['default']
    UIcon: typeof import('./../../node_modules/.pnpm/@nuxt+ui@4.5.1_@tiptap+extensions@3.20.1_@tiptap+core@3.20.1_@tiptap+pm@3.20.1__@tiptap_1b0adad71e75a16afa4f2635bf844052/node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
  }
}
